In [1]:
import pandas as pd

In [2]:
import numpy as np
from scipy.signal import argrelmax, argrelmin

In [3]:
tdf = pd.read_csv('bitcoin.csv').tail(100)
tdf.columns = [col.lower() for col in tdf.columns]
tdf

,date,open,high,low,close,volume
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084
...,...,...,...,...,...,...
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218


In [4]:
tdf.head(20)

,date,open,high,low,close,volume
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084
36073,2021-10-03 11:00:00,47812.32,48048.00,47778.05,47974.86,972.55548
36074,2021-10-03 12:00:00,47974.86,48090.00,47808.14,47964.43,804.97466
36075,2021-10-03 13:00:00,47964.44,48150.00,47841.00,48052.50,1147.51808
36076,2021-10-03 14:00:00,48052.50,48105.60,47892.99,47965.64,997.50451
36077,2021-10-03 15:00:00,47965.64,48025.31,47799.18,47879.82,1251.80495


In [5]:
tdf.tail(10)

,date,open,high,low,close,volume
36158,2021-10-07 00:00:00,55315.00,55332.31,54500.00,54794.88,3291.49488
36159,2021-10-07 01:00:00,54794.88,54909.19,54112.00,54787.30,2806.59176
36160,2021-10-07 02:00:00,54787.30,55230.60,54680.92,55075.56,1938.38290
36161,2021-10-07 03:00:00,55075.57,55215.67,54730.86,54810.94,1540.73481
36162,2021-10-07 04:00:00,54810.93,55237.04,54756.06,55073.20,1450.00390
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218
36167,2021-10-07 09:00:00,54538.31,54547.30,53786.13,53995.50,2739.15361


In [6]:
high_idx = argrelmax(tdf['high'].values, order= 2)[0]

In [7]:
arr = np.array((14, 21, 37, 22, 30, 55, 53, 71, 52, 31, 21, 10, 4, 9, 11, 41, 58, 66, 73, 91, 100, 111))

In [8]:
rs = argrelmax(arr, order=2)

In [9]:
rs

(array([2, 7], dtype=int64),)

In [10]:

tdf

,date,open,high,low,close,volume
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084
...,...,...,...,...,...,...
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218


In [11]:
high_idx = argrelmax(tdf['high'].values, order= 2)[0]

In [12]:
high_idx

array([ 7, 11, 23, 26, 36, 42, 52, 56, 63, 71, 79, 86, 89, 94],
      dtype=int64)

In [13]:

def calc_high_idx(index, high_idx):
    high_idx_v = [np.nan]*len(index)
    start_idx = high_idx[0]
    for i, idx in enumerate(high_idx):
        if i == 0:
            continue
        # tdf.iloc[start_idx:idx, tdf.columns.get_loc('high_idx')]= high_idx[i-1]
        high_idx_v[start_idx: idx] = [high_idx[i-1]]*(idx- start_idx)
        start_idx = idx
    # tdf.iloc[start_idx:, tdf.columns.get_loc('high_idx')] = high_idx[-1]
    high_idx_v[start_idx:] = [high_idx[-1]]*(len(high_idx_v) - start_idx)
    return high_idx_v

In [14]:
arr = np.full(10, np.nan)
arr

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [15]:
arr[0: 2] = 1 

In [16]:
type(arr[0])

numpy.float64

In [17]:
def calc_high_idx(index, high_idx):
    high_idx_v = np.full(len(index), 0)

    start_idx = high_idx[0]
    for i, idx in enumerate(high_idx):
        if i == 0:
            continue
        high_idx_v[start_idx: idx] = high_idx[i-1]
        start_idx = idx

    high_idx_v[start_idx:] = high_idx[-1]
    return high_idx_v

In [18]:
rs = calc_high_idx(tdf, high_idx)
rs

array([ 0,  0,  0,  0,  0,  0,  0,  7,  7,  7,  7, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 23, 23, 23, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 36, 36, 36, 36, 36, 36, 42, 42, 42, 42, 42, 42, 42, 42, 42,
       42, 52, 52, 52, 52, 56, 56, 56, 56, 56, 56, 56, 63, 63, 63, 63, 63,
       63, 63, 63, 71, 71, 71, 71, 71, 71, 71, 71, 79, 79, 79, 79, 79, 79,
       79, 86, 86, 86, 89, 89, 89, 89, 89, 94, 94, 94, 94, 94, 94])

In [19]:
rs

array([ 0,  0,  0,  0,  0,  0,  0,  7,  7,  7,  7, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 23, 23, 23, 26, 26, 26, 26, 26, 26, 26, 26,
       26, 26, 36, 36, 36, 36, 36, 36, 42, 42, 42, 42, 42, 42, 42, 42, 42,
       42, 52, 52, 52, 52, 56, 56, 56, 56, 56, 56, 56, 63, 63, 63, 63, 63,
       63, 63, 63, 71, 71, 71, 71, 71, 71, 71, 71, 79, 79, 79, 79, 79, 79,
       79, 86, 86, 86, 89, 89, 89, 89, 89, 94, 94, 94, 94, 94, 94])

In [20]:
tdf['high_idx'] = rs

In [21]:
tdf.head(20)

,date,open,high,low,close,volume,high_idx
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0
36073,2021-10-03 11:00:00,47812.32,48048.00,47778.05,47974.86,972.55548,0
36074,2021-10-03 12:00:00,47974.86,48090.00,47808.14,47964.43,804.97466,0
36075,2021-10-03 13:00:00,47964.44,48150.00,47841.00,48052.50,1147.51808,7
36076,2021-10-03 14:00:00,48052.50,48105.60,47892.99,47965.64,997.50451,7
36077,2021-10-03 15:00:00,47965.64,48025.31,47799.18,47879.82,1251.80495,7


In [22]:
tdf.tail(30)

,date,open,high,low,close,volume,high_idx
36138,2021-10-06 04:00:00,51512.13,51593.52,51236.70,51325.83,1788.572970,63
36139,2021-10-06 05:00:00,51325.82,51828.00,51200.56,51512.37,3845.981640,71
36140,2021-10-06 06:00:00,51516.11,51736.11,51450.85,51509.98,1795.945490,71
36141,2021-10-06 07:00:00,51509.97,51575.10,51088.00,51449.99,2514.708150,71
36142,2021-10-06 08:00:00,51450.00,51500.00,50420.00,50693.51,4693.989210,71
36143,2021-10-06 09:00:00,50695.74,50822.00,50382.41,50700.00,3309.284380,71
36144,2021-10-06 10:00:00,50700.00,51478.00,50619.10,51160.35,3675.566410,71
36145,2021-10-06 11:00:00,51160.35,51490.00,51091.30,51306.56,2864.515720,71
36146,2021-10-06 12:00:00,51306.57,52829.00,51259.84,52741.68,7188.980390,71
36147,2021-10-06 13:00:00,52741.68,55555.00,52610.20,53997.00,13067.382057,79


In [23]:
tdf['test'] = np.nan

In [24]:
tdf

,date,open,high,low,close,volume,high_idx,test
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0,NaN
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0,NaN
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0,NaN
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0,NaN
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0,NaN
...,...,...,...,...,...,...,...,...
36163,2021-10-07 05:00:00,55073.20,55073.21,54545.07,54735.76,2251.12202,94,NaN
36164,2021-10-07 06:00:00,54735.77,54968.06,54375.83,54534.16,1783.00426,94,NaN
36165,2021-10-07 07:00:00,54534.16,54793.26,54235.33,54755.92,4163.43136,94,NaN
36166,2021-10-07 08:00:00,54755.91,54778.91,54400.00,54538.30,2049.38218,94,NaN


In [30]:
def assign_idx(df: pd.DataFrame, idx_arr, col: str) -> [float]:
    idx_v = np.full(len(df), 0)
    start_idx = idx_arr[0]
    print(f'{col}_idx_arr: {idx_arr}')
    for i, idx in enumerate(idx_arr):
        if i == 0:
            continue
        print(f'赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: {df.iloc[idx_arr[i-1], df.columns.get_loc(col)]}')
        idx_v[start_idx: idx] = df.iloc[idx_arr[i-1], df.columns.get_loc(col)]
        start_idx = idx
    idx_v[start_idx:] = df.iloc[idx_arr[-1], df.columns.get_loc(col)]
    return idx_v
    
def get_range(dataframe: pd.DataFrame):
    df = dataframe.copy()
    if 'range_top' not in df.columns:
        df['range_top'] = np.nan
    if 'range_bottom' not in df.columns:
        df['range_bottom'] = np.nan
    high_idx = argrelmax(df['high'].values, order= 2)[0]
    low_idx = argrelmin(df['low'].values, order= 2)[0]
    # assign idx_v to dataframe
    df['range_top'] = assign_idx(df, high_idx, 'high')
    df['range_bottom'] = assign_idx(df, low_idx, 'low')
    return df[['range_top', 'range_bottom']]

In [31]:
rs = get_range(tdf)

high_idx_arr: [ 7 11 23 26 36 42 52 56 63 71 79 86 89 94]
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 48150.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49228.08
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47865.51
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47962.51
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49536.12
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 49799.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50350.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 50388.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 51886.3
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 51828.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55555.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55386.86
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 55750.0
low_idx_arr: [ 3  9 15 22 26 29 33 39 56 67 75 91]
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47600.0
赋值df.iloc[idx_arr[i-1], df.columns.get_loc(col)]: 47799.18
赋值df.iloc[idx_a

In [34]:
tdf[['range_top', 'range_bottom']] = rs

In [37]:
tdf.head(31)

,date,open,high,low,close,volume,high_idx,test,range_top,range_bottom
36068,2021-10-03 06:00:00,47990.13,48057.00,47896.93,47972.99,617.25174,0,NaN,0,0
36069,2021-10-03 07:00:00,47970.15,47970.16,47814.00,47895.99,569.31948,0,NaN,0,0
36070,2021-10-03 08:00:00,47896.00,47983.38,47798.50,47823.99,838.17079,0,NaN,0,0
36071,2021-10-03 09:00:00,47823.98,47869.00,47600.00,47830.09,1489.72226,0,NaN,0,47600
36072,2021-10-03 10:00:00,47830.09,47953.20,47730.00,47812.32,625.24084,0,NaN,0,47600
36073,2021-10-03 11:00:00,47812.32,48048.00,47778.05,47974.86,972.55548,0,NaN,0,47600
36074,2021-10-03 12:00:00,47974.86,48090.00,47808.14,47964.43,804.97466,0,NaN,0,47600
36075,2021-10-03 13:00:00,47964.44,48150.00,47841.00,48052.50,1147.51808,7,NaN,48150,47600
36076,2021-10-03 14:00:00,48052.50,48105.60,47892.99,47965.64,997.50451,7,NaN,48150,47600
36077,2021-10-03 15:00:00,47965.64,48025.31,47799.18,47879.82,1251.80495,7,NaN,48150,47799
